var articles=[
    {
        title:"А",
        link:"a.html"
    },
    {
        title:"Б",
        link:"б.html" 
    },
    {
        title:"В",
        link:"в.html"
    },
    {
        title:"Г",
        link:"г.html"
    },
    {
        title:"Д",
        link:"д.html"
    },
    {
        title:"Е",
        link:"е.html"
    },
    {
        title:"Ж",
        link:"ж.html"
    },
    {
        title:"З",
        link:"з.html"
    },
    {
        title:"И",
        link:"и.html"
    },
    {
        title:"К",
        link:"к.html"
    },
    {
        title:"Л",
        link:"л.html"
    },
    {
        title:"М",
        link:"м.html"
    },
    {
        title:"Н",
        link:"н.html"
    },
    {
        title:"O",
        link:"o.html"
    },
    {
        title:"П",
        link:"п.html"
    },
    {
        title:"Р",
        link:"р.html"
    },
    {
        title:"С",
        link:"с.html"
    },
    {
        title:"Т",
        link:"т.html"
    },
    {
        title:"У",
        link:"у.html"
    },
    {
        title:"Ф",
        link:"ф.html"
    },
    {
        title:"Ц",
        link:"ц.html"
    },
    {
        title:"Э",
        link:"э.html"
    },
]
var blog='<ul>',
    article,
    amountofarticle=articles.length
 for(article=0;article<amountofarticle;article++) {
     blog+=`
     <li class="letterItem">
         <a href="articles/${articles[article].link}" class="article"
            <h3>${articles[article].title}<h3>
         </a>
    </li>
    `

}
blog+='</ul>'
var root=document.getElementById('root').innerHTML=blog;